server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eFurniture?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: phat1910
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  expiration: 259200  #30 days
  secretKey: dcmmcsmcbylvnkthak


